### PR TITLE
use newer version of packages and get better experience in test case!

### PR DESCRIPTION
**Pull request by sohrabafard**

### CODE REVIEW

**Comment by akhoury** [comment]
there many of reason why I forked html-md and now I am use my fork.
What are the test cases that look "better"?

**Comment by akhoury** [comment]
read this: https://github.com/akhoury/html-md-optional_window#actually

**Comment by akhoury** [comment]
Im thinking on switching to https://github.com/domchristie/to-markdown when doing
HTML ----> Markdown

But i have yet to find a really good one that does
BBcode -----> HTML 
very well.

I'll take a look at this too https://github.com/akhoury/bbcode-to-markdown/issues/5

**Comment by sohrabafard** [comment]
I test it on some of posts that imported from vBulletin to nodebb!

for example output of https://github.com/akhoury/bbcode-to-markdown/issues/5 is:

``` markdown
**[foo bar zee (77.77mb)][0]**


[0]: http://www.example.com/example.mov

```

**Comment by akhoury** [comment]
no need, i switched to using [to-markdown](https://github.com/domchristie/to-markdown)

**Comment by akhoury** [comment]
Thank you though

**Pull request closed without merging**
